// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e01a80d1-cff1-4620-a0ab-9d92e4d309ef",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qiDhw2oVt",
    "aws_user_pools_web_client_id": "2t98v269tfui6iae8mjjib4ot4",
    "oauth": {
        "domain": "ssm-session-manager-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:8080/home/",
        "redirectSignOut": "http://localhost:8080/bye/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
